#!/usr/bin/env bash

source bash_aliases
source fzf_related
source utilities
source google_cloud
source k8s

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

export NVM_DIR="/Users/sendhil/.nvm"
export GOPATH=$HOME/go
export PATH=$PATH:~/.cargo/bin:$GOPATH/bin:~/src/google-cloud-sdk/bin
